export enum RiskSeverity {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
}

export enum RiskType {
  MISSING_CLAUSE = 'MISSING_CLAUSE',
  DEVIATION = 'DEVIATION',
  COMPLIANCE_ISSUE = 'COMPLIANCE_ISSUE',
  AMBIGUOUS_LANGUAGE = 'AMBIGUOUS_LANGUAGE',
  UNFAIR_TERMS = 'UNFAIR_TERMS',
  DATA_PROTECTION = 'DATA_PROTECTION',
  INTELLECTUAL_PROPERTY = 'INTELLECTUAL_PROPERTY',
  LIABILITY = 'LIABILITY',
  TERMINATION = 'TERMINATION',
  OTHER = 'OTHER',
}
